spring.application.name=MedicalClinic
#
# JDBC properties
#
spring.datasource.url={}
spring.datasource.username={}
spring.datasource.password={}



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={}
spring.mail.password={}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# Show SQL statements
spring.jpa.show-sql=true

# Format SQL statements for easier reading
spring.jpa.properties.hibernate.format_sql=true

# Enable logging of SQL exceptions
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.web=DEBUG
